#服务中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/cui2000/springclouddemo
          searchPaths: config-server/properties
  application:
    name: config-server